name = 'erika-florist-api'
main = "build/index.js"
compatibility_date = "2025-02-16"

[vars]

routes = [{ pattern = "api.erika.florist/*", zone_name = "erika.florist" }]

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"
