name = "erika-florist"
compatibility_date = "2024-02-15"

[assets]
directory = "./dist"

[build]
command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . $HOME/.cargo/env && cargo run --release"
