name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "rust-toolchain*"
      - "crates/**/*"
      - ".github/workflows/deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-test-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Deploy Website
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./crates/website
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Backend
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./crates/backend
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
