name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "crates/**/*"
      - ".github/workflows/deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      website: ${{ steps.filter.outputs.website }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - "Cargo.toml"
              - "Cargo.lock"
              - "rust-toolchain.toml"
              - "crates/backend/**/*"
            website:
              - "Cargo.toml"
              - "Cargo.lock"
              - "rust-toolchain.toml"
              - "crates/website/**/*"

  deploy:
    needs: changes
    if: (needs.changes.outputs.backend == 'true' || needs.changes.outputs.website == 'true') && !contains(github.event.head_commit.message, '[skip cd]')
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-test-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Deploy Website
        if: needs.changes.outputs.website == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./crates/website
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Backend
        if: needs.changes.outputs.backend == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./crates/backend
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
